name: Bygg og deploy

on:
  push:
    branches:
      - main         # Push events on master branch
    
jobs:
  release-notes:
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: write
    steps:
      - name: Release Drafter
        uses: release-drafter/release-drafter@v6
        id: drafter

  build:
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 21
          cache: maven
      
      - name: Hent tag    
        run: echo "TAG=$(date +%Y.%m.%d.%H%M%S)-$(echo $GITHUB_SHA | cut -c1-7)" >> $GITHUB_ENV
       
      - name: Bygg og test
        shell: bash
        run: |
          echo "Building $(echo $GITHUB_SHA | cut -c1-7)"
          mvn   deploy   --batch-mode 
          echo "Bygget og testet"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
