name: Lag release

on:
  release:
    types: [published]

jobs:
  publish-release:
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    permissions:
      contents: read
      packages: write
    steps:
            
      - name: Checkout latest code
        uses: actions/checkout@v4
        with:
          ref: main

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 21

      - name: Publish artifact
        env:
          NEW_VERSION: ${{ github.event.release.tag_name }}
        run:  |
          mvn -B versions:set -DnewVersion="$NEW_VERSION"
          mvn -B versions:commit
          mvn  --batch-mode deploy

        #run:  mvn  --batch-mode -DreleaseVersion=${NEW_VERSION}  -DignoreSnapshots=true release:prepare release:perform
