name: Lag release

on:
  release:
    types: [published]

jobs:
  publish-release:
    runs-on: ubuntu-latest
    permissions:
        id-token: write
        contents: write
        packages: write
    steps:
            
      - name: Checkout latest code
        uses: actions/checkout@v4
        with:
          ref: main

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 21

      - name: Configure Git user
        run: |
            git config user.email "actions@github.com"
            git config user.name "GitHub Actions"
            
      - name: Publish artifact
        env:
          GITHUB_ACTOR: ${{ github.actor }}
          NEW_VERSION: ${{ github.event.release.tag_name }}
          GITHUB_TOKEN: ${{ env.GITHUB_TOKEN }}
        run:  |
          mvn -B versions:set -DnewVersion="$NEW_VERSION"
          mvn -B versions:commit
          mvn  --batch-mode deploy

        #run:  mvn  --batch-mode -DreleaseVersion=${NEW_VERSION}  -DignoreSnapshots=true release:prepare release:perform
