name: Lag release

on:
  release:
    types: [published]

jobs:
  publish-release:
    runs-on: ubuntu-latest
    env:
      NEW_VERSION: ${{ github.event.release.tag_name }}
    permissions:
      contents: write
      packages: write
    steps:
            
      - name: Checkout latest code
        uses: actions/checkout@v4
        with:
          ref: main

      - name: Setup build cache
        uses: actions/cache@v2
        with:
            path: ~/.m2/repository
            key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
            restore-keys: |
              ${{ runner.os }}-maven-     
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 21

      - name: Publish artifact
        run: |
          git config --global user.email "actions@github.com"
          git config --global user.name "GitHub Actions release"
          mvn  --settings /home/runner/.m2/settings.xml --batch-mode -DreleaseVersion=${NEW_VERSION}  release:prepare release:perform
     
